name: amelia build
on: [workflow_dispatch]
jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
    # - uses: actions/checkout@v3    
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} default-route-openshift-image-registry.apps.cloud.waw.pl.gsni.kyndryl.net
        export AML_IMAGE_TAG=0.0.0.5
        export AML_REPOSITORY=default-route-openshift-image-registry.apps.cloud.waw.pl.gsni.kyndryl.net/aml
        export AML_PROJECT_PATH=/home/marcin/gsni-okd/amelia
        /home/marcin/gsni-okd/amelia-images-build.sh
        /home/marcin/gsni-okd/amelia-images-push.sh
        unset AML_IMAGE_TAG AML_REPOSITORY AML_PROJECT_PATH
