name: amelia build
on: [workflow_dispatch]
jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
    # - uses: actions/checkout@v3    
    - name: build docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "start"
        echo $(whoami)
        echo $(pwd)
        # docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} default-route-openshift-image-registry.apps.cloud.waw.pl.gsni.kyndryl.net
        echo test01 
        AML_IMAGE_TAG=$(date '+%Y%m%d.%H%M')
        echo ${AML_IMAGE_TAG} >> $GITHUB_OUTPUT
        export AML_REPOSITORY=default-route-openshift-image-registry.apps.cloud.waw.pl.gsni.kyndryl.net/aml
        export AML_PROJECT_PATH=/home/marcin/gsni-okd/amelia
        # /home/marcin/gsni-okd/amelia-images-build.sh
        # /home/marcin/gsni-okd/amelia-images-push.sh
        echo ${AML_IMAGE_TAG}
        unset AML_REPOSITORY    
        echo "end"
  deploy:
    runs-on: self-hosted
    steps:  
    - name: deploy
      run: |
        echo "start"
        echo $GITHUB_OUTPUT
        echo ${DOCKER_USERNAME} 
        echo ${DOCKER_PASSWORD}
        echo ${AML_IMAGE_TAG}
        echo ${AML_REPOSITORY}
        echo ${AML_PROJECT_PATH}
        echo "end"
    
