name: MK Test Docker Image CI
on: [workflow_dispatch]
jobs:
  build:
    name: Build Application
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: ..\..\..\scripts\build.bat
      shell: cmd
