name: MK Test Docker Image CI
on: [workflow_dispatch]
jobs:
  build:
    name: Build Application
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: |
        export TAG=0.0.0.5
        /home/marcin/gsni-okd/amelia-images-build.sh
        unset TAG
        
